version: '3.3'
services:
    # WebServers hosting OWASP Juice shop application
    juice1:
        hostname: juiceserver1
        image: bkimminich/juice-shop
    
    elk:
        image: sebp/elk:742
        hostname: elk
        mem_limit: 4g
        restart: always
        volumes:
          - ./logstash/conf.d:/etc/logstash/conf.d:ro
          - elk:/var/lib/elasticsearch
        ports:
          - 9200:9200
          - 5601:5601
          - 5144:5144

    # NGINX Plus Load Balancer
    nginx-plus:
        hostname: nginx-plus
        build: nginx-plus
        volumes:
            - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d
            - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
            - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:8080
            - 80:80
            - 443:443
        restart: always
volumes:
    elk: