version: '3.3'
services:
    # WebServers hosting OWASP Juice shop application
    juice1:
        hostname: juiceserver1
        image: bkimminich/juice-shop

    # dvwa1:
    #     hostname: DVWAServer1
    #     image: vulnerables/web-dvwa
        
    # NGINX Plus Load Balancer
    nginx-plus-dos:
        hostname: nginx-plus-dos
        build: 
           context: nginx-plus
           dockerfile: Dockerfile_ubuntu
        #    dockerfile: Dockerfile_centos
        volumes:
            - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d
            - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
            - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        # privileged: true #uncomment this for L4 accelerated mitigation
        ports:
            - 8080:8080
            - 80:80
            - 443:443
        restart: always
