version: '3.3'
services:
    # WebServers hosting OWASP Juice shop application
    juice1:
        hostname: juiceserver1
        image: bkimminich/juice-shop
    
    elk:
        image: sebp/elk:792
        container_name: elk
        hostname: elk
        # mem_limit: 4g
        restart: always
        volumes:
          - ./elk/logstash/conf.d:/etc/logstash/conf.d:ro
          - ./elk/elasticsearch:/var/lib/elasticsearch
          - ./elk/kibana/kibana.yml:/opt/kibana/config/kibana.yml
        expose:
            - 5601
            - 9200
            - 5044
            - 5145 # NGINX syslog
            - 5144 # WAF logs
        ports:
          - 9200:9200
          - 5601:5601
          - 5144:5144
        healthcheck:
            test: "wget -qO- http://localhost:5601 > /dev/null"
            interval: 30s
            timeout: 10s
            retries: 10

    dvwa1:
        hostname: DVWAServer1
        image: vulnerables/web-dvwa
        
    # NGINX Plus Load Balancer
    nginx-plus:
        hostname: nginx-plus
        build: nginx-plus
        volumes:
            - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d
            - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
            - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:8080
            - 80:80
            - 443:443
        restart: always
# volumes:
#     elk: