
# For CentOS 7:
FROM centos:centos7

LABEL maintainer="sh.dutta@f5.com"

# Download certificate and key from the customer portal (https://cs.nginx.com)
# and copy to the build context:
COPY etc/ssl/nginx/nginx-repo.* /etc/ssl/nginx/
RUN chmod 644 /etc/ssl/nginx/* 

# Install prerequisite packages:
RUN yum -y install wget ca-certificates epel-release

# Add NGINX Plus repo to Yum:
RUN wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/nginx-plus-7.4.repo

# Add NGINX App-protect repo to Yum:
RUN wget -P /etc/yum.repos.d https://cs.nginx.com/static/files/app-protect-7.repo

# Install NGINX App Protect WAF:
RUN yum -y install app-protect \
    && yum clean all \
    && rm -rf /var/cache/yum

# Remove nginx repository key/cert from docker
RUN rm -rf /etc/ssl/nginx

# Forward request logs to Docker log collector:
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

# Copy configuration files:
COPY etc/nginx /etc/nginx

# COPY entrypoint.sh file:
COPY entrypoint.sh /root/

CMD ["sh", "/root/entrypoint.sh"]